// Muffin Nursery — Category Configuration
// Botanical categories for collectors

export const plantCategories = [
  {
    id: "aroids",
    slug: "aroids",
    name: "Aroids",
    description: "The classics — Monstera, Philodendron, and Anthurium. Statement leaves for tropical vibes.",
    image: "https://images.unsplash.com/photo-1614594975525-e45190c55d0b?w=800&q=80",
    sortOrder: 1,
    isActive: true,
  },
  {
    id: "sansevierias",
    slug: "sansevierias",
    name: "Sansevierias",
    description: "Practically unkillable. Tolerates low light, forgetful watering, and busy lives.",
    image: "https://images.unsplash.com/photo-1599598425947-240a7d7c5b1d?w=800&q=80",
    sortOrder: 2,
    isActive: true,
  },
  {
    id: "agave",
    slug: "agave",
    name: "Agave",
    description: "Architectural succulents with striking silhouettes. Sun lovers for bright spaces.",
    image: "https://images.unsplash.com/photo-1509423355108-b389831e6077?w=800&q=80",
    sortOrder: 3,
    isActive: true,
  },
  {
    id: "mangave",
    slug: "mangave",
    name: "Mangave",
    description: "Rare hybrids — the best of both worlds. Collectors' favorites.",
    image: "https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=800&q=80",
    sortOrder: 4,
    isActive: true,
  },
  {
    id: "adenium",
    slug: "adenium",
    name: "Adenium",
    description: "Desert rose — sculptural trunk with vibrant flowers. Thrives in Karachi heat.",
    image: "https://images.unsplash.com/photo-1563951027628-5686a967c-72e?w=800&q=80",
    sortOrder: 5,
    isActive: true,
  },
  {
    id: "hoya",
    slug: "hoya",
    name: "Hoya",
    description: "Wax plants with porcelain-like blooms. Perfect for hanging baskets.",
    image: "https://images.unsplash.com/photo-1612361806066-9fa5f68b463e?w=800&q=80",
    sortOrder: 6,
    isActive: true,
  },
  {
    id: "orchids",
    slug: "orchids",
    name: "Orchids",
    description: "Elegant and lasting. Local varieties adapted to Karachi conditions.",
    image: "https://images.unsplash.com/photo-1566928409869-6279f5b6a8a8?w=800&q=80",
    sortOrder: 7,
    isActive: true,
  },
  {
    id: "cacti-succulents",
    slug: "cacti-succulents",
    name: "Cacti & Succulents",
    description: "Everything else — echeverias, haworthias, and unique specimens.",
    image: "https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=800&q=80",
    sortOrder: 8,
    isActive: true,
  },
]

export const useCaseCategories = [
  {
    id: "low-light",
    slug: "low-light-survivors",
    name: "Low Light Survivors",
    description: "Plants that thrive even when your space doesn't have much sun.",
    icon: "Cloud",
    sortOrder: 1,
  },
  {
    id: "balcony",
    slug: "balcony-rooftop",
    name: "Balcony & Rooftop",
    description: "Wind-tolerant and full-sun lovers for outdoor spaces.",
    icon: "Sun",
    sortOrder: 2,
  },
  {
    id: "air-purifying",
    slug: "air-purifying",
    name: "Air Purifying",
    description: "NASA-approved air cleaners for your home.",
    icon: "Wind",
    sortOrder: 3,
  },
  {
    id: "pet-safe",
    slug: "pet-safe",
    name: "Pet Safe",
    description: "Non-toxic plants safe for cats, dogs, and curious kids.",
    icon: "Heart",
    sortOrder: 4,
  },
  {
    id: "beginner",
    slug: "beginner-proof",
    name: "Beginner Proof",
    description: "Forgiving plants that bounce back from mistakes.",
    icon: "Sparkles",
    sortOrder: 5,
  },
  {
    id: "statement",
    slug: "statement-plants",
    name: "Statement Plants",
    description: "Big, bold, conversation-starting specimens.",
    icon: "Crown",
    sortOrder: 6,
  },
]

export const moodCategories = [
  { id: "soft-mood", slug: "soft", name: "Soft", description: "Gentle, muted, calming greens" },
  { id: "bright-mood", slug: "bright", name: "Bright", description: "Vibrant, energizing, sunny" },
  { id: "moody", slug: "moody", name: "Moody", description: "Dark, dramatic, mysterious" },
]
